///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//package com.bluewalrus.main;
//
//import com.bluewalrus.chart.BubbleChart;
//
///**
// *
// * @author lauren
// */
//public class BottomControls extends javax.swing.JPanel {
//
//    BubbleChart chart;
//
//    /**
//     * Creates new form BottomControls
//     */
//    public BottomControls(BubbleChart cfs) {
//
//        this.chart = cfs;
//
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        minXValueField = new javax.swing.JTextField();
//        jLabel2 = new javax.swing.JLabel();
//        minYValueField = new javax.swing.JTextField();
//        jLabel3 = new javax.swing.JLabel();
//        maxXValueField = new javax.swing.JTextField();
//        jLabel4 = new javax.swing.JLabel();
//        maxYValueField = new javax.swing.JTextField();
//        jLabel5 = new javax.swing.JLabel();
//        applyButton = new javax.swing.JButton();
//        jTabbedPane1 = new javax.swing.JTabbedPane();
//        jPanel1 = new javax.swing.JPanel();
//        x1IncField = new javax.swing.JTextField();
//        x2IncField = new javax.swing.JTextField();
//        x3IncField = new javax.swing.JTextField();
//        jLabel1 = new javax.swing.JLabel();
//        jLabel6 = new javax.swing.JLabel();
//        jLabel7 = new javax.swing.JLabel();
//        jPanel2 = new javax.swing.JPanel();
//
//        minXValueField.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                minXValueFieldActionPerformed(evt);
//            }
//        });
//
//        jLabel2.setText("min. Y Value");
//
//        jLabel3.setText("max. Y Value");
//
//        jLabel4.setText("max. X Value");
//
//        maxYValueField.setText(" ");
//        maxYValueField.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                maxYValueFieldActionPerformed(evt);
//            }
//        });
//
//        jLabel5.setText("min. X Value");
//
//        applyButton.setText("Apply");
//        applyButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                applyButtonActionPerformed(evt);
//            }
//        });
//
//        x1IncField.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                x1IncFieldActionPerformed(evt);
//            }
//        });
//
//        x2IncField.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                x2IncFieldActionPerformed(evt);
//            }
//        });
//
//        x3IncField.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                x3IncFieldActionPerformed(evt);
//            }
//        });
//
//        jLabel1.setText("X Primary Increments");
//
//        jLabel6.setText("X Primary Secondary Increments");
//
//        jLabel7.setText("X Primary Tertiary Increments");
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                .addContainerGap(253, Short.MAX_VALUE)
//                .addComponent(x3IncField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(82, 82, 82))
//            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                .addGroup(jPanel1Layout.createSequentialGroup()
//                    .addContainerGap()
//                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel1Layout.createSequentialGroup()
//                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                .addComponent(jLabel6)
//                                .addComponent(jLabel1))
//                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                .addComponent(x2IncField, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
//                                .addComponent(x1IncField)))
//                        .addComponent(jLabel7))
//                    .addContainerGap(82, Short.MAX_VALUE)))
//        );
//        jPanel1Layout.setVerticalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                .addContainerGap(76, Short.MAX_VALUE)
//                .addComponent(x3IncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap())
//            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                .addGroup(jPanel1Layout.createSequentialGroup()
//                    .addContainerGap()
//                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                        .addComponent(jLabel1)
//                        .addComponent(x1IncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                    .addGap(1, 1, 1)
//                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                        .addComponent(jLabel6)
//                        .addComponent(x2IncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                    .addComponent(jLabel7)
//                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
//        );
//
//        jTabbedPane1.addTab("tab1", jPanel1);
//
//        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
//        jPanel2.setLayout(jPanel2Layout);
//        jPanel2Layout.setHorizontalGroup(
//            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 385, Short.MAX_VALUE)
//        );
//        jPanel2Layout.setVerticalGroup(
//            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 118, Short.MAX_VALUE)
//        );
//
//        jTabbedPane1.addTab("tab2", jPanel2);
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
//        this.setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(3, 3, 3)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(jLabel2)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addComponent(minYValueField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(jLabel5)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addComponent(minXValueField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                        .addGap(76, 76, 76)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(jLabel4)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addComponent(maxXValueField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
//                            .addGroup(layout.createSequentialGroup()
//                                .addComponent(jLabel3)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addComponent(maxYValueField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                        .addGap(145, 145, 145))
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addContainerGap())))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(minXValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(maxXValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(jLabel4)
//                            .addComponent(jLabel5))
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(jLabel2)
//                            .addComponent(minYValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(jLabel3)
//                            .addComponent(maxYValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
//                    .addGroup(layout.createSequentialGroup()
//                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addComponent(applyButton)))
//                .addContainerGap())
//        );
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void x1IncFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1IncFieldActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_x1IncFieldActionPerformed
//
//    private void minXValueFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minXValueFieldActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_minXValueFieldActionPerformed
//
//    private void x2IncFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x2IncFieldActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_x2IncFieldActionPerformed
//
//    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
//
//        try {
//            int x1 = new Integer(minXValueField.getText());
//            int y1 = new Integer(minYValueField.getText());
//            int x2 = new Integer(maxXValueField.getText());
//            int y2 = new Integer(maxYValueField.getText());
//
//            chart.xAxis.minValue = x1;
//            chart.xAxis.maxValue = x2;
//
//            chart.yAxis.minValue = y1;
//            chart.yAxis.maxValue = y2;
//            
//            chart.repaint();
//
//        } catch (Exception e) {
//
//            e.printStackTrace();
//        }
//
////        x1IncField.getText();
////        x2IncField.getText();
////        x3IncField.getText();
//        //apply
//// TODO add your handling code here:
//    }//GEN-LAST:event_applyButtonActionPerformed
//
//    private void x3IncFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x3IncFieldActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_x3IncFieldActionPerformed
//
//    private void maxYValueFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxYValueFieldActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_maxYValueFieldActionPerformed
//
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JButton applyButton;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JLabel jLabel6;
//    private javax.swing.JLabel jLabel7;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JPanel jPanel2;
//    private javax.swing.JTabbedPane jTabbedPane1;
//    private javax.swing.JTextField maxXValueField;
//    private javax.swing.JTextField maxYValueField;
//    private javax.swing.JTextField minXValueField;
//    private javax.swing.JTextField minYValueField;
//    private javax.swing.JTextField x1IncField;
//    private javax.swing.JTextField x2IncField;
//    private javax.swing.JTextField x3IncField;
//    // End of variables declaration//GEN-END:variables
//}
